/**
 * Built-in polar library.
 *
 * IMPORTANT, and worth repeating in the UI: **none of these are measured polars.**
 * Every entry below is generated by `generatePolar` from the class's published
 * dimensions (LOA, LWL, displacement, working sail area) using the parametric model in
 * docs/02-data-sources/polars.md §2.5. They are plausible, not accurate. Their job is to
 * let someone route their first leg before they have ever heard the word "polar", and to
 * act as the prior that real data — a class polar, an ORC certificate, or a fit to the
 * sailor's own tracks — overwrites.
 *
 * Nothing here is copied from Expedition, qtVlm, OpenCPN, ORC or any other polar set.
 * Dimensions are public class-association / manufacturer specification figures; the
 * numbers in the tables are ours.
 *
 * Displacement figures for dinghies and catamarans include a nominal crew weight,
 * because sail-area/displacement ratio is meaningless for a 59 kg hull sailed by an
 * 80 kg human. Sail area is working sail (main + jib/genoa); the shape templates already
 * account for spinnakers downwind.
 */

import { generatePolar } from '../lib/polar'
import type { BoatDims, BoatType } from '../lib/polar'
import type { PolarTable } from '../lib/types'

export interface PolarLibraryEntry {
  id: string
  name: string
  type: BoatType
  loaM: number
  polar: PolarTable
}

interface LibrarySpec {
  id: string
  name: string
  dims: BoatDims
  /** Where the dimensions came from, and anything worth knowing about the fit. */
  note: string
}

const SPECS: readonly LibrarySpec[] = [
  {
    id: 'optimist',
    name: 'Optimist',
    dims: { type: 'dinghy', loaM: 2.31, lwlM: 2.3, beamM: 1.13, dispKg: 90, sailAreaM2: 3.3 },
    note: 'Generated. IODA class dimensions; 35 kg hull + ~55 kg sailor and gear.',
  },
  {
    id: 'ilca7',
    name: 'ILCA 7 (Laser)',
    dims: { type: 'dinghy', loaM: 4.23, lwlM: 3.81, beamM: 1.42, dispKg: 139, sailAreaM2: 7.06 },
    note: 'Generated. ILCA class dimensions; 59 kg hull + 80 kg sailor. Standard rig.',
  },
  {
    id: '420',
    name: 'Club 420',
    dims: { type: 'dinghy', loaM: 4.2, lwlM: 4.01, beamM: 1.63, dispKg: 230, sailAreaM2: 10.25 },
    note: 'Generated. Class dimensions; 100 kg hull + 130 kg two-up crew. Main + jib.',
  },
  {
    id: '29er',
    name: '29er',
    dims: { type: 'sportboat', loaM: 4.4, lwlM: 4.35, beamM: 1.77, dispKg: 200, sailAreaM2: 12.5 },
    note:
      'Generated. Class dimensions; 70 kg hull + 130 kg crew. Uses the sportboat shape ' +
      'because a trapeze skiff sails hot asymmetric angles downwind, not dinghy angles.',
  },
  {
    id: 'j70',
    name: 'J/70',
    dims: { type: 'sportboat', loaM: 6.93, lwlM: 5.79, beamM: 2.25, dispKg: 794, sailAreaM2: 21.9 },
    note: 'Generated. J/Boats published dimensions; main 13.9 + jib 8.0 m².',
  },
  {
    id: 'melges24',
    name: 'Melges 24',
    dims: { type: 'sportboat', loaM: 7.54, lwlM: 6.86, beamM: 2.49, dispKg: 794, sailAreaM2: 25.9 },
    note: 'Generated. Class dimensions; main 17.5 + jib 8.4 m².',
  },
  {
    id: 'j105',
    name: 'J/105',
    dims: { type: 'keelboat', loaM: 10.52, lwlM: 8.66, beamM: 3.35, dispKg: 3357, sailAreaM2: 51.2 },
    note: 'Generated. J/Boats published dimensions; main 30.0 + jib 21.2 m².',
  },
  {
    id: 'first-36-7',
    name: 'Beneteau First 36.7',
    dims: { type: 'keelboat', loaM: 11.0, lwlM: 9.6, beamM: 3.55, dispKg: 5150, sailAreaM2: 63 },
    note: 'Generated. Manufacturer dimensions; main 33 + genoa 30 m². Cruiser-racer.',
  },
  {
    id: 'cruiser-40',
    name: 'Generic 40 ft cruiser',
    dims: { type: 'cruiser', loaM: 12.2, lwlM: 10.6, beamM: 3.9, dispKg: 8200, sailAreaM2: 78 },
    note:
      'Generated from typical production-cruiser dimensions rather than any one boat. ' +
      'This is the honest default for "I have a 40 footer and no idea".',
  },
  {
    id: 'nacra17',
    name: 'Nacra 17',
    dims: { type: 'multihull', loaM: 5.25, lwlM: 5.25, beamM: 2.59, dispKg: 317, sailAreaM2: 18.5 },
    note:
      'Generated. Class dimensions; 172 kg platform + 145 kg crew. The model has no ' +
      'concept of foiling, so treat the top end as conservative.',
  },
  {
    id: 'f18',
    name: 'Formula 18 catamaran',
    dims: { type: 'multihull', loaM: 5.52, lwlM: 5.52, beamM: 2.6, dispKg: 325, sailAreaM2: 21.15 },
    note: 'Generated. F18 box-rule dimensions; 180 kg platform + 145 kg crew.',
  },
]

/**
 * The library, built once at module load.
 *
 * Generation is a few hundred float operations per boat, so doing it eagerly costs less
 * than the bytes a hand-written table would have taken in the bundle.
 */
export const POLAR_LIBRARY: PolarLibraryEntry[] = SPECS.map((s) => {
  const polar = generatePolar(s.dims, s.name)
  polar.source = `${s.note} Parametric model: docs/02-data-sources/polars.md §2.5.`
  return { id: s.id, name: s.name, type: s.dims.type, loaM: s.dims.loaM, polar }
})

const BY_ID = new Map(POLAR_LIBRARY.map((e) => [e.id, e]))

/** Look up a built-in polar by its stable id. Ids are persisted in boat setup. */
export function findPolar(id: string): PolarLibraryEntry | undefined {
  return BY_ID.get(id)
}
